// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbpuowevqoumttfgrgnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicHVvd2V2cW91bXR0ZmdyZ25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTUwNjIsImV4cCI6MjA2NzAzMTA2Mn0.ZsxHKxzOn3FMZo95yj55uFBcaR3-SxZRlBDBwLSlMkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});